// Aliases for standard integer types
typedef unsigned char uint8_t;  // 8-bit unsigned
typedef unsigned int uint32_t;  // 32-bit unsigned
typedef uint32_t size_t;        // type used for sizes and memory lengths

// Symbols defined by the linker
extern char __bss[], __bss_end[], __stack_top[];
// __bss[]      : start address of uninitialized global/static variables (.bss section)
// __bss_end[]  : end address of .bss section
// __stack_top  : top address of the stack memory in RAM (stack grows downward)

// Fill a memory buffer with a byte value
void *memset(void *buf, char c, size_t n) {
    uint8_t *p = (uint8_t *) buf; // pointer to iterate over memory
    while (n--) {                 // loop n times
        *p++ = c;                 // set each byte to the value c
    }
    return buf;                    // return the starting address of the buffer
}

// Main kernel function
void kernel_main(void) {
    // Initialize all uninitialized globals (.bss) to zero
    memset(__bss, 0, (size_t) __bss_end - (size_t) __bss);

    for (;;) ; // Infinite loop to keep the kernel running
}

// Boot function executed at CPU startup
__attribute__((section(".text.boot"))) // place this function in .text.boot section
__attribute__((naked))                 // no prologue/epilogue generated by compiler
void boot(void) {
    __asm__ __volatile__( // inline assembly, volatile = do not reorder or optimize
        "mv sp, %[stack_top]\n"  // set the CPU stack pointer to top of stack
        "j kernel_main\n"        // jump directly to kernel_main function
        :
        : [stack_top] "r" (__stack_top) // input: pass RAM address of stack top
    );
}

/*
Explanation of boot function:

- At this point, the CPU has just started. C runtime (stack, globals) is not ready.
- Inline assembly is used because we need to directly manipulate CPU registers.
- __volatile__ ensures the compiler executes these instructions exactly in order.
- mv sp, %[stack_top] sets the CPU's stack pointer register (sp) to the RAM address of the top of stack (__stack_top). 
- j kernel_main jumps directly to kernel_main where normal C code can safely run.
- Naked attribute prevents the compiler from adding function setup/cleanup (prologue/epilogue), which would break low-level booting.
*/

